My/pay as bid
BESTenergytrade/integritee-cli-py pull request #3
Opened 2023-08-16 15:50 UTC by m-yahya

This will add CLI commands to call the Rust CLI.

2023-08-21 09:00 UTC, j-ti commented
Solves https://github.com/olisystems/BEST-Energy/issues/40

2023-08-23 13:11 UTC, j-ti requested changes
It works
Requested changes 
- mostly update of comments
- adding return values e.g. in python dict type

2023-08-23 13:11 UTC, j-ti commented on src/lib.rs
>  // We need to fill in some actual meaningful values.
comment above not valid anymore

2023-08-23 13:11 UTC, j-ti commented on src/lib.rs
> +) -> PyResult<()> {
Should return value e.g. the created `account` string (which could be put also inside a dictionary) or the matches as Python Dict/List:
Could be similar to the following example for returning a python List of dictionaries:
```
    // Convert MarketOutput to Python List of Dict representing matches
    let pyMatches = PyList::new(py,
        matches.matches.into_iter().map(|mtch| {
            let dict = PyDict::new(py);
            dict.set_item("time", mtch.energy_kwh);
            dict.set_item("bid_id", mtch.bid_id);
            dict.set_item("ask_id", mtch.ask_id);
            dict.set_item("bid_actor", "");
            dict.set_item("ask_actor", "");
            dict.set_item("bid_cluster", 0);
            dict.set_item("ask_cluster", 0);
            dict.set_item("energy", mtch.energy_kwh);
            dict.set_item("price", mtch.price_euro_per_kwh);
            dict.set_item("included_grid_fee", 0);
            dict
        })
    );
```
As both types are different the account string or the match list could be it self returned within a dictionary with a specific key, i.e. {"account": account_string} or {"matches": pyMatches}

2023-08-23 13:11 UTC, j-ti commented on .env.example
> +NODE_URL=
default values or comment regarding formatting

2023-08-23 13:11 UTC, j-ti commented on README.md
> +## Run the Client
rename "Run as Command Line Tool"

2023-08-23 13:11 UTC, j-ti commented on README.md
> +
new subsection
`### Example Commands`

2023-08-23 13:11 UTC, j-ti commented on README.md
> +## Using Environment Variables
insert section below within "Run as Command Line Tool"
i.e. `### Setup Environment Variables`

2023-08-23 13:11 UTC, j-ti commented on src/lib.rs
>          // random mrenclave, has to be replaced with one that has been fetched from the chain.
update comment

2023-08-23 13:11 UTC, j-ti commented on src/lib.rs
>          // always be used without first creating them in the keystore.
Add comment explaining that //Alice is not actually the account to be created here, but that it is used as signer for the trusted call

2023-08-23 13:11 UTC, j-ti commented on src/lib.rs
> +) -> PyResult<()> {
with the adapted algorithm, I might add some information to the matches returned by simplyr-lib both for pay as bid as well as the cluster-based matching

2023-08-23 13:23 UTC, m-yahya commented on src/lib.rs
>  // We need to fill in some actual meaningful values.
Removed.

2023-08-23 13:28 UTC, m-yahya commented on .env.example
> +NODE_URL=
Default values added.

2023-08-23 13:28 UTC, m-yahya commented on README.md
> +## Run the Client
Renamed.

2023-08-23 13:29 UTC, m-yahya commented on README.md
> +
Example commands added.

2023-08-23 13:29 UTC, m-yahya commented on README.md
> +## Using Environment Variables
Please take a look at the updated `README` file.

2023-08-23 13:31 UTC, m-yahya commented on src/lib.rs
>          // random mrenclave, has to be replaced with one that has been fetched from the chain.
Comment updated.

2023-08-23 13:33 UTC, m-yahya commented on src/lib.rs
>          // always be used without first creating them in the keystore.
updated

2023-08-24 09:09 UTC, j-ti reviewed
- I propose to merge https://github.com/BESTenergytrade/integritee-cli-py/pull/4 first
- https://github.com/BESTenergytrade/integritee-cli-py/pull/3/files#r1302951203  can be changed in subsequent PR

2023-08-24 09:09 UTC, j-ti commented on src/lib.rs
> +) -> PyResult<()> {
Created issue https://github.com/BESTenergytrade/integritee-cli-py/issues/5 can be changed in subsequent PR

2023-08-24 09:33 UTC, merged